### ISSUE TITLE
Use of Wikimedia imagery

### ISSUE THREAD

**Issue by Quaffel** [Quaffel/get-me-drunk-efficiently#34]
The documentation claims that the Wikimedia API is used to provide images of the cocktails. At present, this isn't the case. Is this something we still want to add to our MVP or should we just remove the corresponding section?

**Comment by Jonasdoubleyou** [comment]
Do we have the URL already? How long would it take to provide it? Frontend is 20mins

**Comment by Quaffel** [comment]
Images of entities are referenced using the standardized ["image"](https://www.wikidata.org/wiki/Property:P18) property. Adding the following line (and the additional query parameter) to the SPARQL query should thus be sufficient to retrieve the URL.

```rq
OPTIONAL { ?cocktail wdt:P18 ?imageUrl. }
```

**Comment by Jonasdoubleyou** [comment]
Then I'd say this is possible today. Also it would be quite fun for the showcase
